CREATE TABLE public.estoque_categorias (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), nome text NOT NULL, descricao text, ativo boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.estoque_localizacoes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), nome text NOT NULL, descricao text, ativo boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.estoque_fornecedores (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), razao_social text NOT NULL, nome_fantasia text, cnpj text, telefone text, celular text, email text, endereco text, cidade text, estado text, observacoes text, ativo boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.estoque_produtos (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), codigo_interno text, codigo_fabricante text, nome text NOT NULL, descricao text, categoria_id uuid REFERENCES public.estoque_categorias(id) ON DELETE SET NULL, marca text, modelo text, unidade text NOT NULL DEFAULT 'UN', estoque_atual numeric NOT NULL DEFAULT 0, estoque_minimo numeric NOT NULL DEFAULT 0, estoque_maximo numeric NOT NULL DEFAULT 0, custo_medio numeric NOT NULL DEFAULT 0, ultima_compra date, localizacao_id uuid REFERENCES public.estoque_localizacoes(id) ON DELETE SET NULL, localizacao text, fornecedor_principal_id uuid REFERENCES public.estoque_fornecedores(id) ON DELETE SET NULL, ativo boolean NOT NULL DEFAULT true, observacao text, status text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.estoque_movimentacoes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), produto_id uuid REFERENCES public.estoque_produtos(id) ON DELETE CASCADE, tipo text NOT NULL, quantidade numeric NOT NULL DEFAULT 0, estoque_anterior numeric, estoque_posterior numeric, valor_total numeric, equipamento_id uuid REFERENCES public.equipamentos(id) ON DELETE SET NULL, responsavel text, documento text, observacao text, data_movimento date DEFAULT current_date, created_by uuid DEFAULT auth.uid(), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.estoque_entradas (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), data date NOT NULL DEFAULT current_date, fornecedor_id uuid REFERENCES public.estoque_fornecedores(id) ON DELETE SET NULL, numero_nf text, serie text, responsavel text, observacao text, created_by uuid DEFAULT auth.uid(), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.estoque_entrada_itens (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), entrada_id uuid NOT NULL REFERENCES public.estoque_entradas(id) ON DELETE CASCADE, produto_id uuid REFERENCES public.estoque_produtos(id) ON DELETE CASCADE, quantidade numeric NOT NULL DEFAULT 0, unidade text DEFAULT 'UN', valor_unitario numeric DEFAULT 0, desconto numeric DEFAULT 0, valor_total numeric DEFAULT 0, localizacao_id uuid REFERENCES public.estoque_localizacoes(id) ON DELETE SET NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.estoque_saidas (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), data date NOT NULL DEFAULT current_date, produto_id uuid REFERENCES public.estoque_produtos(id) ON DELETE CASCADE, quantidade numeric NOT NULL DEFAULT 0, motivo text, responsavel text, equipamento_id uuid REFERENCES public.equipamentos(id) ON DELETE SET NULL, horimetro text, manutencao_relacionada text, observacao text, created_by uuid DEFAULT auth.uid(), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.estoque_saida_itens (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), saida_id uuid NOT NULL REFERENCES public.estoque_saidas(id) ON DELETE CASCADE, produto_id uuid REFERENCES public.estoque_produtos(id) ON DELETE CASCADE, quantidade numeric NOT NULL DEFAULT 0, unidade text DEFAULT 'UN', valor_unitario numeric DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.estoque_transferencias (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), produto_id uuid REFERENCES public.estoque_produtos(id) ON DELETE CASCADE, origem_id uuid REFERENCES public.estoque_localizacoes(id) ON DELETE SET NULL, destino_id uuid REFERENCES public.estoque_localizacoes(id) ON DELETE SET NULL, quantidade numeric NOT NULL DEFAULT 0, responsavel text, data date DEFAULT current_date, observacao text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.estoque_inventarios (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), produto_id uuid REFERENCES public.estoque_produtos(id) ON DELETE CASCADE, data date DEFAULT current_date, quantidade_anterior numeric, quantidade_nova numeric, diferenca numeric, motivo text, responsavel text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.estoque_pneus (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), codigo text NOT NULL, marca text, modelo text, medida text, codigo_serie text, dot text, tipo text, valor numeric DEFAULT 0, fornecedor_id uuid REFERENCES public.estoque_fornecedores(id) ON DELETE SET NULL, data_compra date, estado text, status text, equipamento_id uuid REFERENCES public.equipamentos(id) ON DELETE SET NULL, observacao text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['estoque_categorias','estoque_localizacoes','estoque_fornecedores','estoque_produtos','estoque_movimentacoes','estoque_entradas','estoque_entrada_itens','estoque_saidas','estoque_saida_itens','estoque_transferencias','estoque_inventarios','estoque_pneus'] LOOP
    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON public.%I TO authenticated', t);
    EXECUTE format('GRANT ALL ON public.%I TO service_role', t);
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('CREATE POLICY "%s_select" ON public.%I FOR SELECT TO authenticated USING (true)', t, t);
    EXECUTE format('CREATE POLICY "%s_insert" ON public.%I FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL)', t, t);
    EXECUTE format('CREATE POLICY "%s_update" ON public.%I FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL)', t, t);
    EXECUTE format('CREATE POLICY "%s_delete" ON public.%I FOR DELETE TO authenticated USING (private.has_role(auth.uid(), ''admin''))', t, t);
  END LOOP;
END $$;

CREATE TRIGGER trg_estoque_produtos_updated BEFORE UPDATE ON public.estoque_produtos FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_estoque_categorias_updated BEFORE UPDATE ON public.estoque_categorias FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_estoque_fornecedores_updated BEFORE UPDATE ON public.estoque_fornecedores FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_estoque_pneus_updated BEFORE UPDATE ON public.estoque_pneus FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
NOTIFY pgrst, 'reload schema';