/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedMedicoesRouteImport } from './routes/_authenticated/medicoes'
import { Route as AuthenticatedFornecedoresRouteImport } from './routes/_authenticated/fornecedores'
import { Route as AuthenticatedEstoqueRouteImport } from './routes/_authenticated/estoque'
import { Route as AuthenticatedCotacoesRouteImport } from './routes/_authenticated/cotacoes'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedNotasFiscaisIndexRouteImport } from './routes/_authenticated/notas-fiscais.index'
import { Route as AuthenticatedEstoqueIndexRouteImport } from './routes/_authenticated/estoque/index'
import { Route as AuthenticatedEquipamentosIndexRouteImport } from './routes/_authenticated/equipamentos.index'
import { Route as AuthenticatedCustosIndexRouteImport } from './routes/_authenticated/custos.index'
import { Route as AuthenticatedCotacoesIndexRouteImport } from './routes/_authenticated/cotacoes.index'
import { Route as AuthenticatedEstoqueTransferenciasRouteImport } from './routes/_authenticated/estoque/transferencias'
import { Route as AuthenticatedEstoqueSaidasRouteImport } from './routes/_authenticated/estoque/saidas'
import { Route as AuthenticatedEstoqueRelatoriosRouteImport } from './routes/_authenticated/estoque/relatorios'
import { Route as AuthenticatedEstoqueProdutosRouteImport } from './routes/_authenticated/estoque/produtos'
import { Route as AuthenticatedEstoquePneusRouteImport } from './routes/_authenticated/estoque/pneus'
import { Route as AuthenticatedEstoqueMovimentacoesRouteImport } from './routes/_authenticated/estoque/movimentacoes'
import { Route as AuthenticatedEstoqueInventarioRouteImport } from './routes/_authenticated/estoque/inventario'
import { Route as AuthenticatedEstoqueFornecedoresRouteImport } from './routes/_authenticated/estoque/fornecedores'
import { Route as AuthenticatedEstoqueEntradasRouteImport } from './routes/_authenticated/estoque/entradas'
import { Route as AuthenticatedEstoqueCategoriasRouteImport } from './routes/_authenticated/estoque/categorias'
import { Route as AuthenticatedEstoqueAlertasRouteImport } from './routes/_authenticated/estoque/alertas'
import { Route as AuthenticatedEquipamentosIdRouteImport } from './routes/_authenticated/equipamentos.$id'
import { Route as AuthenticatedNotasFiscaisIdIndexRouteImport } from './routes/_authenticated/notas-fiscais.$id.index'
import { Route as AuthenticatedEquipamentosIdIndexRouteImport } from './routes/_authenticated/equipamentos.$id.index'
import { Route as AuthenticatedCotacoesIdIndexRouteImport } from './routes/_authenticated/cotacoes.$id.index'
import { Route as AuthenticatedEquipamentosIdManutencaoRouteImport } from './routes/_authenticated/equipamentos.$id.manutencao'
import { Route as AuthenticatedEquipamentosIdHistoricoRouteImport } from './routes/_authenticated/equipamentos.$id.historico'
import { Route as AuthenticatedEquipamentosIdHistoricoHistIdRouteImport } from './routes/_authenticated/equipamentos.$id.historico.$histId'
import { Route as AuthenticatedSrcRoutesAuthenticatedFornecedoresNovoRouteImport } from './routes/_authenticated/src/routes/_authenticated/fornecedores/novo'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMedicoesRoute = AuthenticatedMedicoesRouteImport.update({
  id: '/medicoes',
  path: '/medicoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFornecedoresRoute =
  AuthenticatedFornecedoresRouteImport.update({
    id: '/fornecedores',
    path: '/fornecedores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstoqueRoute = AuthenticatedEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCotacoesRoute = AuthenticatedCotacoesRouteImport.update({
  id: '/cotacoes',
  path: '/cotacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotasFiscaisIndexRoute =
  AuthenticatedNotasFiscaisIndexRouteImport.update({
    id: '/notas-fiscais/',
    path: '/notas-fiscais/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstoqueIndexRoute =
  AuthenticatedEstoqueIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEstoqueRoute,
  } as any)
const AuthenticatedEquipamentosIndexRoute =
  AuthenticatedEquipamentosIndexRouteImport.update({
    id: '/equipamentos/',
    path: '/equipamentos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustosIndexRoute =
  AuthenticatedCustosIndexRouteImport.update({
    id: '/custos/',
    path: '/custos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCotacoesIndexRoute =
  AuthenticatedCotacoesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCotacoesRoute,
  } as any)
const AuthenticatedEstoqueTransferenciasRoute =
  AuthenticatedEstoqueTransferenciasRouteImport.update({
    id: '/transferencias',
    path: '/transferencias',
    getParentRoute: () => AuthenticatedEstoqueRoute,
  } as any)
const AuthenticatedEstoqueSaidasRoute =
  AuthenticatedEstoqueSaidasRouteImport.update({
    id: '/saidas',
    path: '/saidas',
    getParentRoute: () => AuthenticatedEstoqueRoute,
  } as any)
const AuthenticatedEstoqueRelatoriosRoute =
  AuthenticatedEstoqueRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedEstoqueRoute,
  } as any)
const AuthenticatedEstoqueProdutosRoute =
  AuthenticatedEstoqueProdutosRouteImport.update({
    id: '/produtos',
    path: '/produtos',
    getParentRoute: () => AuthenticatedEstoqueRoute,
  } as any)
const AuthenticatedEstoquePneusRoute =
  AuthenticatedEstoquePneusRouteImport.update({
    id: '/pneus',
    path: '/pneus',
    getParentRoute: () => AuthenticatedEstoqueRoute,
  } as any)
const AuthenticatedEstoqueMovimentacoesRoute =
  AuthenticatedEstoqueMovimentacoesRouteImport.update({
    id: '/movimentacoes',
    path: '/movimentacoes',
    getParentRoute: () => AuthenticatedEstoqueRoute,
  } as any)
const AuthenticatedEstoqueInventarioRoute =
  AuthenticatedEstoqueInventarioRouteImport.update({
    id: '/inventario',
    path: '/inventario',
    getParentRoute: () => AuthenticatedEstoqueRoute,
  } as any)
const AuthenticatedEstoqueFornecedoresRoute =
  AuthenticatedEstoqueFornecedoresRouteImport.update({
    id: '/fornecedores',
    path: '/fornecedores',
    getParentRoute: () => AuthenticatedEstoqueRoute,
  } as any)
const AuthenticatedEstoqueEntradasRoute =
  AuthenticatedEstoqueEntradasRouteImport.update({
    id: '/entradas',
    path: '/entradas',
    getParentRoute: () => AuthenticatedEstoqueRoute,
  } as any)
const AuthenticatedEstoqueCategoriasRoute =
  AuthenticatedEstoqueCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AuthenticatedEstoqueRoute,
  } as any)
const AuthenticatedEstoqueAlertasRoute =
  AuthenticatedEstoqueAlertasRouteImport.update({
    id: '/alertas',
    path: '/alertas',
    getParentRoute: () => AuthenticatedEstoqueRoute,
  } as any)
const AuthenticatedEquipamentosIdRoute =
  AuthenticatedEquipamentosIdRouteImport.update({
    id: '/equipamentos/$id',
    path: '/equipamentos/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotasFiscaisIdIndexRoute =
  AuthenticatedNotasFiscaisIdIndexRouteImport.update({
    id: '/notas-fiscais/$id/',
    path: '/notas-fiscais/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipamentosIdIndexRoute =
  AuthenticatedEquipamentosIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEquipamentosIdRoute,
  } as any)
const AuthenticatedCotacoesIdIndexRoute =
  AuthenticatedCotacoesIdIndexRouteImport.update({
    id: '/$id/',
    path: '/$id/',
    getParentRoute: () => AuthenticatedCotacoesRoute,
  } as any)
const AuthenticatedEquipamentosIdManutencaoRoute =
  AuthenticatedEquipamentosIdManutencaoRouteImport.update({
    id: '/manutencao',
    path: '/manutencao',
    getParentRoute: () => AuthenticatedEquipamentosIdRoute,
  } as any)
const AuthenticatedEquipamentosIdHistoricoRoute =
  AuthenticatedEquipamentosIdHistoricoRouteImport.update({
    id: '/historico',
    path: '/historico',
    getParentRoute: () => AuthenticatedEquipamentosIdRoute,
  } as any)
const AuthenticatedEquipamentosIdHistoricoHistIdRoute =
  AuthenticatedEquipamentosIdHistoricoHistIdRouteImport.update({
    id: '/$histId',
    path: '/$histId',
    getParentRoute: () => AuthenticatedEquipamentosIdHistoricoRoute,
  } as any)
const AuthenticatedSrcRoutesAuthenticatedFornecedoresNovoRoute =
  AuthenticatedSrcRoutesAuthenticatedFornecedoresNovoRouteImport.update({
    id: '/src/routes/_authenticated/fornecedores/novo',
    path: '/src/routes/fornecedores/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/cotacoes': typeof AuthenticatedCotacoesRouteWithChildren
  '/estoque': typeof AuthenticatedEstoqueRouteWithChildren
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/medicoes': typeof AuthenticatedMedicoesRoute
  '/equipamentos/$id': typeof AuthenticatedEquipamentosIdRouteWithChildren
  '/estoque/alertas': typeof AuthenticatedEstoqueAlertasRoute
  '/estoque/categorias': typeof AuthenticatedEstoqueCategoriasRoute
  '/estoque/entradas': typeof AuthenticatedEstoqueEntradasRoute
  '/estoque/fornecedores': typeof AuthenticatedEstoqueFornecedoresRoute
  '/estoque/inventario': typeof AuthenticatedEstoqueInventarioRoute
  '/estoque/movimentacoes': typeof AuthenticatedEstoqueMovimentacoesRoute
  '/estoque/pneus': typeof AuthenticatedEstoquePneusRoute
  '/estoque/produtos': typeof AuthenticatedEstoqueProdutosRoute
  '/estoque/relatorios': typeof AuthenticatedEstoqueRelatoriosRoute
  '/estoque/saidas': typeof AuthenticatedEstoqueSaidasRoute
  '/estoque/transferencias': typeof AuthenticatedEstoqueTransferenciasRoute
  '/cotacoes/': typeof AuthenticatedCotacoesIndexRoute
  '/custos/': typeof AuthenticatedCustosIndexRoute
  '/equipamentos/': typeof AuthenticatedEquipamentosIndexRoute
  '/estoque/': typeof AuthenticatedEstoqueIndexRoute
  '/notas-fiscais/': typeof AuthenticatedNotasFiscaisIndexRoute
  '/equipamentos/$id/historico': typeof AuthenticatedEquipamentosIdHistoricoRouteWithChildren
  '/equipamentos/$id/manutencao': typeof AuthenticatedEquipamentosIdManutencaoRoute
  '/cotacoes/$id/': typeof AuthenticatedCotacoesIdIndexRoute
  '/equipamentos/$id/': typeof AuthenticatedEquipamentosIdIndexRoute
  '/notas-fiscais/$id/': typeof AuthenticatedNotasFiscaisIdIndexRoute
  '/equipamentos/$id/historico/$histId': typeof AuthenticatedEquipamentosIdHistoricoHistIdRoute
  '/src/routes/fornecedores/novo': typeof AuthenticatedSrcRoutesAuthenticatedFornecedoresNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/medicoes': typeof AuthenticatedMedicoesRoute
  '/estoque/alertas': typeof AuthenticatedEstoqueAlertasRoute
  '/estoque/categorias': typeof AuthenticatedEstoqueCategoriasRoute
  '/estoque/entradas': typeof AuthenticatedEstoqueEntradasRoute
  '/estoque/fornecedores': typeof AuthenticatedEstoqueFornecedoresRoute
  '/estoque/inventario': typeof AuthenticatedEstoqueInventarioRoute
  '/estoque/movimentacoes': typeof AuthenticatedEstoqueMovimentacoesRoute
  '/estoque/pneus': typeof AuthenticatedEstoquePneusRoute
  '/estoque/produtos': typeof AuthenticatedEstoqueProdutosRoute
  '/estoque/relatorios': typeof AuthenticatedEstoqueRelatoriosRoute
  '/estoque/saidas': typeof AuthenticatedEstoqueSaidasRoute
  '/estoque/transferencias': typeof AuthenticatedEstoqueTransferenciasRoute
  '/cotacoes': typeof AuthenticatedCotacoesIndexRoute
  '/custos': typeof AuthenticatedCustosIndexRoute
  '/equipamentos': typeof AuthenticatedEquipamentosIndexRoute
  '/estoque': typeof AuthenticatedEstoqueIndexRoute
  '/notas-fiscais': typeof AuthenticatedNotasFiscaisIndexRoute
  '/equipamentos/$id/historico': typeof AuthenticatedEquipamentosIdHistoricoRouteWithChildren
  '/equipamentos/$id/manutencao': typeof AuthenticatedEquipamentosIdManutencaoRoute
  '/cotacoes/$id': typeof AuthenticatedCotacoesIdIndexRoute
  '/equipamentos/$id': typeof AuthenticatedEquipamentosIdIndexRoute
  '/notas-fiscais/$id': typeof AuthenticatedNotasFiscaisIdIndexRoute
  '/equipamentos/$id/historico/$histId': typeof AuthenticatedEquipamentosIdHistoricoHistIdRoute
  '/src/routes/fornecedores/novo': typeof AuthenticatedSrcRoutesAuthenticatedFornecedoresNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/cotacoes': typeof AuthenticatedCotacoesRouteWithChildren
  '/_authenticated/estoque': typeof AuthenticatedEstoqueRouteWithChildren
  '/_authenticated/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/_authenticated/medicoes': typeof AuthenticatedMedicoesRoute
  '/_authenticated/equipamentos/$id': typeof AuthenticatedEquipamentosIdRouteWithChildren
  '/_authenticated/estoque/alertas': typeof AuthenticatedEstoqueAlertasRoute
  '/_authenticated/estoque/categorias': typeof AuthenticatedEstoqueCategoriasRoute
  '/_authenticated/estoque/entradas': typeof AuthenticatedEstoqueEntradasRoute
  '/_authenticated/estoque/fornecedores': typeof AuthenticatedEstoqueFornecedoresRoute
  '/_authenticated/estoque/inventario': typeof AuthenticatedEstoqueInventarioRoute
  '/_authenticated/estoque/movimentacoes': typeof AuthenticatedEstoqueMovimentacoesRoute
  '/_authenticated/estoque/pneus': typeof AuthenticatedEstoquePneusRoute
  '/_authenticated/estoque/produtos': typeof AuthenticatedEstoqueProdutosRoute
  '/_authenticated/estoque/relatorios': typeof AuthenticatedEstoqueRelatoriosRoute
  '/_authenticated/estoque/saidas': typeof AuthenticatedEstoqueSaidasRoute
  '/_authenticated/estoque/transferencias': typeof AuthenticatedEstoqueTransferenciasRoute
  '/_authenticated/cotacoes/': typeof AuthenticatedCotacoesIndexRoute
  '/_authenticated/custos/': typeof AuthenticatedCustosIndexRoute
  '/_authenticated/equipamentos/': typeof AuthenticatedEquipamentosIndexRoute
  '/_authenticated/estoque/': typeof AuthenticatedEstoqueIndexRoute
  '/_authenticated/notas-fiscais/': typeof AuthenticatedNotasFiscaisIndexRoute
  '/_authenticated/equipamentos/$id/historico': typeof AuthenticatedEquipamentosIdHistoricoRouteWithChildren
  '/_authenticated/equipamentos/$id/manutencao': typeof AuthenticatedEquipamentosIdManutencaoRoute
  '/_authenticated/cotacoes/$id/': typeof AuthenticatedCotacoesIdIndexRoute
  '/_authenticated/equipamentos/$id/': typeof AuthenticatedEquipamentosIdIndexRoute
  '/_authenticated/notas-fiscais/$id/': typeof AuthenticatedNotasFiscaisIdIndexRoute
  '/_authenticated/equipamentos/$id/historico/$histId': typeof AuthenticatedEquipamentosIdHistoricoHistIdRoute
  '/_authenticated/src/routes/_authenticated/fornecedores/novo': typeof AuthenticatedSrcRoutesAuthenticatedFornecedoresNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/cotacoes'
    | '/estoque'
    | '/fornecedores'
    | '/medicoes'
    | '/equipamentos/$id'
    | '/estoque/alertas'
    | '/estoque/categorias'
    | '/estoque/entradas'
    | '/estoque/fornecedores'
    | '/estoque/inventario'
    | '/estoque/movimentacoes'
    | '/estoque/pneus'
    | '/estoque/produtos'
    | '/estoque/relatorios'
    | '/estoque/saidas'
    | '/estoque/transferencias'
    | '/cotacoes/'
    | '/custos/'
    | '/equipamentos/'
    | '/estoque/'
    | '/notas-fiscais/'
    | '/equipamentos/$id/historico'
    | '/equipamentos/$id/manutencao'
    | '/cotacoes/$id/'
    | '/equipamentos/$id/'
    | '/notas-fiscais/$id/'
    | '/equipamentos/$id/historico/$histId'
    | '/src/routes/fornecedores/novo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/fornecedores'
    | '/medicoes'
    | '/estoque/alertas'
    | '/estoque/categorias'
    | '/estoque/entradas'
    | '/estoque/fornecedores'
    | '/estoque/inventario'
    | '/estoque/movimentacoes'
    | '/estoque/pneus'
    | '/estoque/produtos'
    | '/estoque/relatorios'
    | '/estoque/saidas'
    | '/estoque/transferencias'
    | '/cotacoes'
    | '/custos'
    | '/equipamentos'
    | '/estoque'
    | '/notas-fiscais'
    | '/equipamentos/$id/historico'
    | '/equipamentos/$id/manutencao'
    | '/cotacoes/$id'
    | '/equipamentos/$id'
    | '/notas-fiscais/$id'
    | '/equipamentos/$id/historico/$histId'
    | '/src/routes/fornecedores/novo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/cotacoes'
    | '/_authenticated/estoque'
    | '/_authenticated/fornecedores'
    | '/_authenticated/medicoes'
    | '/_authenticated/equipamentos/$id'
    | '/_authenticated/estoque/alertas'
    | '/_authenticated/estoque/categorias'
    | '/_authenticated/estoque/entradas'
    | '/_authenticated/estoque/fornecedores'
    | '/_authenticated/estoque/inventario'
    | '/_authenticated/estoque/movimentacoes'
    | '/_authenticated/estoque/pneus'
    | '/_authenticated/estoque/produtos'
    | '/_authenticated/estoque/relatorios'
    | '/_authenticated/estoque/saidas'
    | '/_authenticated/estoque/transferencias'
    | '/_authenticated/cotacoes/'
    | '/_authenticated/custos/'
    | '/_authenticated/equipamentos/'
    | '/_authenticated/estoque/'
    | '/_authenticated/notas-fiscais/'
    | '/_authenticated/equipamentos/$id/historico'
    | '/_authenticated/equipamentos/$id/manutencao'
    | '/_authenticated/cotacoes/$id/'
    | '/_authenticated/equipamentos/$id/'
    | '/_authenticated/notas-fiscais/$id/'
    | '/_authenticated/equipamentos/$id/historico/$histId'
    | '/_authenticated/src/routes/_authenticated/fornecedores/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/medicoes': {
      id: '/_authenticated/medicoes'
      path: '/medicoes'
      fullPath: '/medicoes'
      preLoaderRoute: typeof AuthenticatedMedicoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fornecedores': {
      id: '/_authenticated/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof AuthenticatedFornecedoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque': {
      id: '/_authenticated/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AuthenticatedEstoqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cotacoes': {
      id: '/_authenticated/cotacoes'
      path: '/cotacoes'
      fullPath: '/cotacoes'
      preLoaderRoute: typeof AuthenticatedCotacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notas-fiscais/': {
      id: '/_authenticated/notas-fiscais/'
      path: '/notas-fiscais'
      fullPath: '/notas-fiscais/'
      preLoaderRoute: typeof AuthenticatedNotasFiscaisIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque/': {
      id: '/_authenticated/estoque/'
      path: '/'
      fullPath: '/estoque/'
      preLoaderRoute: typeof AuthenticatedEstoqueIndexRouteImport
      parentRoute: typeof AuthenticatedEstoqueRoute
    }
    '/_authenticated/equipamentos/': {
      id: '/_authenticated/equipamentos/'
      path: '/equipamentos'
      fullPath: '/equipamentos/'
      preLoaderRoute: typeof AuthenticatedEquipamentosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/custos/': {
      id: '/_authenticated/custos/'
      path: '/custos'
      fullPath: '/custos/'
      preLoaderRoute: typeof AuthenticatedCustosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cotacoes/': {
      id: '/_authenticated/cotacoes/'
      path: '/'
      fullPath: '/cotacoes/'
      preLoaderRoute: typeof AuthenticatedCotacoesIndexRouteImport
      parentRoute: typeof AuthenticatedCotacoesRoute
    }
    '/_authenticated/estoque/transferencias': {
      id: '/_authenticated/estoque/transferencias'
      path: '/transferencias'
      fullPath: '/estoque/transferencias'
      preLoaderRoute: typeof AuthenticatedEstoqueTransferenciasRouteImport
      parentRoute: typeof AuthenticatedEstoqueRoute
    }
    '/_authenticated/estoque/saidas': {
      id: '/_authenticated/estoque/saidas'
      path: '/saidas'
      fullPath: '/estoque/saidas'
      preLoaderRoute: typeof AuthenticatedEstoqueSaidasRouteImport
      parentRoute: typeof AuthenticatedEstoqueRoute
    }
    '/_authenticated/estoque/relatorios': {
      id: '/_authenticated/estoque/relatorios'
      path: '/relatorios'
      fullPath: '/estoque/relatorios'
      preLoaderRoute: typeof AuthenticatedEstoqueRelatoriosRouteImport
      parentRoute: typeof AuthenticatedEstoqueRoute
    }
    '/_authenticated/estoque/produtos': {
      id: '/_authenticated/estoque/produtos'
      path: '/produtos'
      fullPath: '/estoque/produtos'
      preLoaderRoute: typeof AuthenticatedEstoqueProdutosRouteImport
      parentRoute: typeof AuthenticatedEstoqueRoute
    }
    '/_authenticated/estoque/pneus': {
      id: '/_authenticated/estoque/pneus'
      path: '/pneus'
      fullPath: '/estoque/pneus'
      preLoaderRoute: typeof AuthenticatedEstoquePneusRouteImport
      parentRoute: typeof AuthenticatedEstoqueRoute
    }
    '/_authenticated/estoque/movimentacoes': {
      id: '/_authenticated/estoque/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/estoque/movimentacoes'
      preLoaderRoute: typeof AuthenticatedEstoqueMovimentacoesRouteImport
      parentRoute: typeof AuthenticatedEstoqueRoute
    }
    '/_authenticated/estoque/inventario': {
      id: '/_authenticated/estoque/inventario'
      path: '/inventario'
      fullPath: '/estoque/inventario'
      preLoaderRoute: typeof AuthenticatedEstoqueInventarioRouteImport
      parentRoute: typeof AuthenticatedEstoqueRoute
    }
    '/_authenticated/estoque/fornecedores': {
      id: '/_authenticated/estoque/fornecedores'
      path: '/fornecedores'
      fullPath: '/estoque/fornecedores'
      preLoaderRoute: typeof AuthenticatedEstoqueFornecedoresRouteImport
      parentRoute: typeof AuthenticatedEstoqueRoute
    }
    '/_authenticated/estoque/entradas': {
      id: '/_authenticated/estoque/entradas'
      path: '/entradas'
      fullPath: '/estoque/entradas'
      preLoaderRoute: typeof AuthenticatedEstoqueEntradasRouteImport
      parentRoute: typeof AuthenticatedEstoqueRoute
    }
    '/_authenticated/estoque/categorias': {
      id: '/_authenticated/estoque/categorias'
      path: '/categorias'
      fullPath: '/estoque/categorias'
      preLoaderRoute: typeof AuthenticatedEstoqueCategoriasRouteImport
      parentRoute: typeof AuthenticatedEstoqueRoute
    }
    '/_authenticated/estoque/alertas': {
      id: '/_authenticated/estoque/alertas'
      path: '/alertas'
      fullPath: '/estoque/alertas'
      preLoaderRoute: typeof AuthenticatedEstoqueAlertasRouteImport
      parentRoute: typeof AuthenticatedEstoqueRoute
    }
    '/_authenticated/equipamentos/$id': {
      id: '/_authenticated/equipamentos/$id'
      path: '/equipamentos/$id'
      fullPath: '/equipamentos/$id'
      preLoaderRoute: typeof AuthenticatedEquipamentosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notas-fiscais/$id/': {
      id: '/_authenticated/notas-fiscais/$id/'
      path: '/notas-fiscais/$id'
      fullPath: '/notas-fiscais/$id/'
      preLoaderRoute: typeof AuthenticatedNotasFiscaisIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipamentos/$id/': {
      id: '/_authenticated/equipamentos/$id/'
      path: '/'
      fullPath: '/equipamentos/$id/'
      preLoaderRoute: typeof AuthenticatedEquipamentosIdIndexRouteImport
      parentRoute: typeof AuthenticatedEquipamentosIdRoute
    }
    '/_authenticated/cotacoes/$id/': {
      id: '/_authenticated/cotacoes/$id/'
      path: '/$id'
      fullPath: '/cotacoes/$id/'
      preLoaderRoute: typeof AuthenticatedCotacoesIdIndexRouteImport
      parentRoute: typeof AuthenticatedCotacoesRoute
    }
    '/_authenticated/equipamentos/$id/manutencao': {
      id: '/_authenticated/equipamentos/$id/manutencao'
      path: '/manutencao'
      fullPath: '/equipamentos/$id/manutencao'
      preLoaderRoute: typeof AuthenticatedEquipamentosIdManutencaoRouteImport
      parentRoute: typeof AuthenticatedEquipamentosIdRoute
    }
    '/_authenticated/equipamentos/$id/historico': {
      id: '/_authenticated/equipamentos/$id/historico'
      path: '/historico'
      fullPath: '/equipamentos/$id/historico'
      preLoaderRoute: typeof AuthenticatedEquipamentosIdHistoricoRouteImport
      parentRoute: typeof AuthenticatedEquipamentosIdRoute
    }
    '/_authenticated/equipamentos/$id/historico/$histId': {
      id: '/_authenticated/equipamentos/$id/historico/$histId'
      path: '/$histId'
      fullPath: '/equipamentos/$id/historico/$histId'
      preLoaderRoute: typeof AuthenticatedEquipamentosIdHistoricoHistIdRouteImport
      parentRoute: typeof AuthenticatedEquipamentosIdHistoricoRoute
    }
    '/_authenticated/src/routes/_authenticated/fornecedores/novo': {
      id: '/_authenticated/src/routes/_authenticated/fornecedores/novo'
      path: '/src/routes/fornecedores/novo'
      fullPath: '/src/routes/fornecedores/novo'
      preLoaderRoute: typeof AuthenticatedSrcRoutesAuthenticatedFornecedoresNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedCotacoesRouteChildren {
  AuthenticatedCotacoesIndexRoute: typeof AuthenticatedCotacoesIndexRoute
  AuthenticatedCotacoesIdIndexRoute: typeof AuthenticatedCotacoesIdIndexRoute
}

const AuthenticatedCotacoesRouteChildren: AuthenticatedCotacoesRouteChildren = {
  AuthenticatedCotacoesIndexRoute: AuthenticatedCotacoesIndexRoute,
  AuthenticatedCotacoesIdIndexRoute: AuthenticatedCotacoesIdIndexRoute,
}

const AuthenticatedCotacoesRouteWithChildren =
  AuthenticatedCotacoesRoute._addFileChildren(
    AuthenticatedCotacoesRouteChildren,
  )

interface AuthenticatedEstoqueRouteChildren {
  AuthenticatedEstoqueAlertasRoute: typeof AuthenticatedEstoqueAlertasRoute
  AuthenticatedEstoqueCategoriasRoute: typeof AuthenticatedEstoqueCategoriasRoute
  AuthenticatedEstoqueEntradasRoute: typeof AuthenticatedEstoqueEntradasRoute
  AuthenticatedEstoqueFornecedoresRoute: typeof AuthenticatedEstoqueFornecedoresRoute
  AuthenticatedEstoqueInventarioRoute: typeof AuthenticatedEstoqueInventarioRoute
  AuthenticatedEstoqueMovimentacoesRoute: typeof AuthenticatedEstoqueMovimentacoesRoute
  AuthenticatedEstoquePneusRoute: typeof AuthenticatedEstoquePneusRoute
  AuthenticatedEstoqueProdutosRoute: typeof AuthenticatedEstoqueProdutosRoute
  AuthenticatedEstoqueRelatoriosRoute: typeof AuthenticatedEstoqueRelatoriosRoute
  AuthenticatedEstoqueSaidasRoute: typeof AuthenticatedEstoqueSaidasRoute
  AuthenticatedEstoqueTransferenciasRoute: typeof AuthenticatedEstoqueTransferenciasRoute
  AuthenticatedEstoqueIndexRoute: typeof AuthenticatedEstoqueIndexRoute
}

const AuthenticatedEstoqueRouteChildren: AuthenticatedEstoqueRouteChildren = {
  AuthenticatedEstoqueAlertasRoute: AuthenticatedEstoqueAlertasRoute,
  AuthenticatedEstoqueCategoriasRoute: AuthenticatedEstoqueCategoriasRoute,
  AuthenticatedEstoqueEntradasRoute: AuthenticatedEstoqueEntradasRoute,
  AuthenticatedEstoqueFornecedoresRoute: AuthenticatedEstoqueFornecedoresRoute,
  AuthenticatedEstoqueInventarioRoute: AuthenticatedEstoqueInventarioRoute,
  AuthenticatedEstoqueMovimentacoesRoute:
    AuthenticatedEstoqueMovimentacoesRoute,
  AuthenticatedEstoquePneusRoute: AuthenticatedEstoquePneusRoute,
  AuthenticatedEstoqueProdutosRoute: AuthenticatedEstoqueProdutosRoute,
  AuthenticatedEstoqueRelatoriosRoute: AuthenticatedEstoqueRelatoriosRoute,
  AuthenticatedEstoqueSaidasRoute: AuthenticatedEstoqueSaidasRoute,
  AuthenticatedEstoqueTransferenciasRoute:
    AuthenticatedEstoqueTransferenciasRoute,
  AuthenticatedEstoqueIndexRoute: AuthenticatedEstoqueIndexRoute,
}

const AuthenticatedEstoqueRouteWithChildren =
  AuthenticatedEstoqueRoute._addFileChildren(AuthenticatedEstoqueRouteChildren)

interface AuthenticatedEquipamentosIdHistoricoRouteChildren {
  AuthenticatedEquipamentosIdHistoricoHistIdRoute: typeof AuthenticatedEquipamentosIdHistoricoHistIdRoute
}

const AuthenticatedEquipamentosIdHistoricoRouteChildren: AuthenticatedEquipamentosIdHistoricoRouteChildren =
  {
    AuthenticatedEquipamentosIdHistoricoHistIdRoute:
      AuthenticatedEquipamentosIdHistoricoHistIdRoute,
  }

const AuthenticatedEquipamentosIdHistoricoRouteWithChildren =
  AuthenticatedEquipamentosIdHistoricoRoute._addFileChildren(
    AuthenticatedEquipamentosIdHistoricoRouteChildren,
  )

interface AuthenticatedEquipamentosIdRouteChildren {
  AuthenticatedEquipamentosIdHistoricoRoute: typeof AuthenticatedEquipamentosIdHistoricoRouteWithChildren
  AuthenticatedEquipamentosIdManutencaoRoute: typeof AuthenticatedEquipamentosIdManutencaoRoute
  AuthenticatedEquipamentosIdIndexRoute: typeof AuthenticatedEquipamentosIdIndexRoute
}

const AuthenticatedEquipamentosIdRouteChildren: AuthenticatedEquipamentosIdRouteChildren =
  {
    AuthenticatedEquipamentosIdHistoricoRoute:
      AuthenticatedEquipamentosIdHistoricoRouteWithChildren,
    AuthenticatedEquipamentosIdManutencaoRoute:
      AuthenticatedEquipamentosIdManutencaoRoute,
    AuthenticatedEquipamentosIdIndexRoute:
      AuthenticatedEquipamentosIdIndexRoute,
  }

const AuthenticatedEquipamentosIdRouteWithChildren =
  AuthenticatedEquipamentosIdRoute._addFileChildren(
    AuthenticatedEquipamentosIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCotacoesRoute: typeof AuthenticatedCotacoesRouteWithChildren
  AuthenticatedEstoqueRoute: typeof AuthenticatedEstoqueRouteWithChildren
  AuthenticatedFornecedoresRoute: typeof AuthenticatedFornecedoresRoute
  AuthenticatedMedicoesRoute: typeof AuthenticatedMedicoesRoute
  AuthenticatedEquipamentosIdRoute: typeof AuthenticatedEquipamentosIdRouteWithChildren
  AuthenticatedCustosIndexRoute: typeof AuthenticatedCustosIndexRoute
  AuthenticatedEquipamentosIndexRoute: typeof AuthenticatedEquipamentosIndexRoute
  AuthenticatedNotasFiscaisIndexRoute: typeof AuthenticatedNotasFiscaisIndexRoute
  AuthenticatedNotasFiscaisIdIndexRoute: typeof AuthenticatedNotasFiscaisIdIndexRoute
  AuthenticatedSrcRoutesAuthenticatedFornecedoresNovoRoute: typeof AuthenticatedSrcRoutesAuthenticatedFornecedoresNovoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCotacoesRoute: AuthenticatedCotacoesRouteWithChildren,
  AuthenticatedEstoqueRoute: AuthenticatedEstoqueRouteWithChildren,
  AuthenticatedFornecedoresRoute: AuthenticatedFornecedoresRoute,
  AuthenticatedMedicoesRoute: AuthenticatedMedicoesRoute,
  AuthenticatedEquipamentosIdRoute:
    AuthenticatedEquipamentosIdRouteWithChildren,
  AuthenticatedCustosIndexRoute: AuthenticatedCustosIndexRoute,
  AuthenticatedEquipamentosIndexRoute: AuthenticatedEquipamentosIndexRoute,
  AuthenticatedNotasFiscaisIndexRoute: AuthenticatedNotasFiscaisIndexRoute,
  AuthenticatedNotasFiscaisIdIndexRoute: AuthenticatedNotasFiscaisIdIndexRoute,
  AuthenticatedSrcRoutesAuthenticatedFornecedoresNovoRoute:
    AuthenticatedSrcRoutesAuthenticatedFornecedoresNovoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
